//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoJuDataEntities : DbContext
    {
        public MoJuDataEntities()
            : base("name=MoJuDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductManage> ProductManage { get; set; }
        public virtual DbSet<UserInfor> UserInfor { get; set; }
        public virtual DbSet<SaleManage> SaleManage { get; set; }
        public virtual DbSet<YearPlan> YearPlan { get; set; }
        public virtual DbSet<ProductQua> ProductQua { get; set; }
        public virtual DbSet<VentureCapa> VentureCapa { get; set; }
        public virtual DbSet<CapCompleteRate> CapCompleteRate { get; set; }
        public virtual DbSet<TimelyRate> TimelyRate { get; set; }
        public virtual DbSet<OtdDpmo> OtdDpmo { get; set; }
    }
}
