//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtdDpmo
    {
        public int ID { get; set; }
        public string FAB_NAME { get; set; }
        public Nullable<double> OTD { get; set; }
        public Nullable<double> DPMO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Ncr { get; set; }
        public Nullable<double> HourYearComplete { get; set; }
        public Nullable<double> HourMonthPlan { get; set; }
        public Nullable<double> HourMonthComplete { get; set; }
        public Nullable<double> JGGSPlan { get; set; }
        public Nullable<double> JGGSComplete { get; set; }
        public Nullable<double> CJGDWPlan { get; set; }
        public Nullable<double> CJGDWComplete { get; set; }
        public Nullable<double> JJGDWPlan { get; set; }
        public Nullable<double> JJGDWComplete { get; set; }
        public Nullable<double> OTDComplete { get; set; }
        public Nullable<double> DPMOCompletefloat { get; set; }
        public Nullable<double> Odds { get; set; }
        public Nullable<double> OddsComplete { get; set; }
    }
}
