//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQua
    {
        public int ID { get; set; }
        public string FAB_NAME { get; set; }
        public string VENTURENAME { get; set; }
        public string OPERATION_NAME { get; set; }
        public Nullable<int> TOTALQTY { get; set; }
        public Nullable<int> QUAQTY { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> RATE { get; set; }
    }
}
