//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductManage
    {
        public string FAB_NAME { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_ID { get; set; }
        public string MACH_TYPE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string MACH_PRO { get; set; }
        public string MATERIAL_ID { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> PROCUT_QUOTA { get; set; }
        public Nullable<double> OUTPUT_VALUE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public Nullable<System.DateTime> PLAN_START { get; set; }
        public Nullable<System.DateTime> PLAN_END { get; set; }
        public Nullable<System.DateTime> PLAN_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string CREATE_USER { get; set; }
        public int ID { get; set; }
        public string VENTURENAME { get; set; }
        public string OPERATIONNAME { get; set; }
    }
}
