//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimelyRate
    {
        public int ID { get; set; }
        public Nullable<double> Week1 { get; set; }
        public Nullable<double> Week2 { get; set; }
        public Nullable<double> Week3 { get; set; }
        public Nullable<double> Week4 { get; set; }
        public Nullable<double> Month1 { get; set; }
        public Nullable<double> RealPlan { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string FAB_NAME { get; set; }
    }
}
