//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentureCapa
    {
        public int ID { get; set; }
        public string FAB_NAME { get; set; }
        public string VENTURENAME { get; set; }
        public string OPERATIONNAME { get; set; }
        public Nullable<double> PROCUT_QUOTA { get; set; }
        public Nullable<double> PROCUT_QUOTA_WEEK { get; set; }
        public Nullable<double> PROCUT_QUOTA_MONTH { get; set; }
    }
}
