//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUIMvc.EmptyProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearPlan
    {
        public int ID { get; set; }
        public string Factory { get; set; }
        public int Year { get; set; }
        public double YearPlan1 { get; set; }
        public double SellYearPlan { get; set; }
    }
}
