//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPLib.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataFromSapEntities : DbContext
    {
        public DataFromSapEntities()
            : base("name=DataFromSapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<View_MBEW> View_MBEW { get; set; }
        public virtual DbSet<View_T_SAP_PP_MaterialMove> View_T_SAP_PP_MaterialMove { get; set; }
        public virtual DbSet<View_T_SAP_PP_ProductOrderHeader> View_T_SAP_PP_ProductOrderHeader { get; set; }
        public virtual DbSet<View_T_SAP_PP_ProductOrderRoute> View_T_SAP_PP_ProductOrderRoute { get; set; }
    }
}
