//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MBEW
    {
        public System.Guid Id { get; set; }
        public string ProductCode { get; set; }
        public string MATNR { get; set; }
        public string BWKEY { get; set; }
        public string BWTAR { get; set; }
        public string STPRS { get; set; }
        public string VERPR { get; set; }
        public string ZPLP1 { get; set; }
        public string VPRSV { get; set; }
        public string PEINH { get; set; }
        public string LVORM { get; set; }
        public string ADD1 { get; set; }
    }
}
