//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_T_SAP_PP_ProductOrderHeader
    {
        public System.Guid Id { get; set; }
        public string ProductCode { get; set; }
        public string AUFNR { get; set; }
        public string AUART { get; set; }
        public string AUTYP { get; set; }
        public string REFNR { get; set; }
        public string ERDAT { get; set; }
        public string AEDAT { get; set; }
        public string MATNR { get; set; }
        public string KTEXT { get; set; }
        public string LTEXT { get; set; }
        public string BUKRS { get; set; }
        public string WERKS { get; set; }
        public string ERNAM { get; set; }
        public string GSBER { get; set; }
        public string GAMNG { get; set; }
        public string GMEIN { get; set; }
        public string VERID { get; set; }
        public string CHARG { get; set; }
        public string KDAUF { get; set; }
        public string KDPOS { get; set; }
        public string KOSTL { get; set; }
        public string PHAS0 { get; set; }
        public string PHAS1 { get; set; }
        public string PHAS2 { get; set; }
        public string PHAS3 { get; set; }
        public string STRMP { get; set; }
        public string ETRMP { get; set; }
        public string FTRMS { get; set; }
        public string GLTRS { get; set; }
        public string IDAT2 { get; set; }
        public string EDATU { get; set; }
        public string LOEKZ { get; set; }
        public string PSMNG { get; set; }
        public string MEINS { get; set; }
        public string GSTRI { get; set; }
        public string GETRI { get; set; }
        public string GLTRI { get; set; }
        public string FTRMI { get; set; }
        public string AUFPL { get; set; }
        public string PLNTY { get; set; }
        public string PLNAL { get; set; }
        public string PVERW { get; set; }
        public string STLAL { get; set; }
        public string STLAN { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string ADD3 { get; set; }
        public string ADD4 { get; set; }
        public string ADD5 { get; set; }
    }
}
