//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_T_SAP_PP_MaterialMove
    {
        public System.Guid Id { get; set; }
        public string ProductCode { get; set; }
        public string MBLNR { get; set; }
        public string MJAHR { get; set; }
        public string BWART { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public string BISMT { get; set; }
        public string MTART { get; set; }
        public string GROES { get; set; }
        public string MVGR2 { get; set; }
        public string MATKL { get; set; }
        public string NTGEW { get; set; }
        public string GEWEI { get; set; }
        public string WERKS { get; set; }
        public string LGORT { get; set; }
        public string CHARG { get; set; }
        public string MENGE { get; set; }
        public string MEINS { get; set; }
        public string DMBTR { get; set; }
        public string PARGB { get; set; }
        public string AUFNR { get; set; }
        public string EBELN { get; set; }
        public Nullable<System.DateTime> BUDAT_MKPF { get; set; }
        public string SAKTO { get; set; }
        public string KOSTL { get; set; }
        public string DISPO { get; set; }
        public string WRKST { get; set; }
        public string ZEINR { get; set; }
        public string BRGEW { get; set; }
        public string SMBLN { get; set; }
        public string ADD0 { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string ADD3 { get; set; }
        public string ADD4 { get; set; }
        public string ADD5 { get; set; }
        public string ADD6 { get; set; }
    }
}
