//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPLib.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_T_SAP_PP_ProductOrderRoute
    {
        public System.Guid Id { get; set; }
        public string ProductCode { get; set; }
        public string AUFNR { get; set; }
        public string AUART { get; set; }
        public string WERKS { get; set; }
        public string BUKRS { get; set; }
        public string ERDAT { get; set; }
        public string OBJNR { get; set; }
        public string KDAUF { get; set; }
        public string KDPOS { get; set; }
        public string KTEXT { get; set; }
        public string LTEXT { get; set; }
        public string MATNR { get; set; }
        public string POSNR { get; set; }
        public string STRMP { get; set; }
        public string ETRMP { get; set; }
        public string CHARG { get; set; }
        public string FTRMI { get; set; }
        public string GAMNG { get; set; }
        public string GMEIN { get; set; }
        public string AUFPL { get; set; }
        public string AUFPL_A { get; set; }
        public string VORNR { get; set; }
        public string STEUS { get; set; }
        public string WEEK_A { get; set; }
        public string KTSCH { get; set; }
        public string LTXA1 { get; set; }
        public string SSAVD { get; set; }
        public string LOEKZ { get; set; }
        public string CPD_UPDAT { get; set; }
        public string ARBPL { get; set; }
        public string KTEXT_C { get; set; }
        public string VGE01 { get; set; }
        public string VGW01 { get; set; }
        public string VGE02 { get; set; }
        public string VGW02 { get; set; }
        public string VGE03 { get; set; }
        public string VGW03 { get; set; }
        public string VGE04 { get; set; }
        public string VGW04 { get; set; }
        public string VGE05 { get; set; }
        public string VGW05 { get; set; }
        public string VGE06 { get; set; }
        public string VGW06 { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
    }
}
